import { jsPDF } from "jspdf";
import type { SiteInsight } from "@/lib/useInsights";
import { estimatedGain, gradeFor, hostOf } from "@/lib/utils";

type JsPDFDoc = jsPDF;

const MARGIN = 48;
const PAGE_H = 792;
const PAGE_W = 612;

function ensureSpace(doc: JsPDFDoc, y: number, need: number): number {
  if (y + need > PAGE_H - MARGIN) {
    doc.addPage();
    return MARGIN;
  }
  return y;
}

function sectionTitle(doc: JsPDFDoc, y: number, title: string): number {
  y = ensureSpace(doc, y, 28);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(15, 23, 42);
  doc.text(title, MARGIN, y);
  return y + 20;
}

function paragraph(
  doc: JsPDFDoc,
  y: number,
  text: string,
  opts?: { size?: number; bold?: boolean; color?: [number, number, number] }
): number {
  const size = opts?.size ?? 10;
  doc.setFont("helvetica", opts?.bold ? "bold" : "normal");
  doc.setFontSize(size);
  doc.setTextColor(...(opts?.color ?? [71, 85, 105]));
  const width = PAGE_W - MARGIN * 2;
  const lines = doc.splitTextToSize(text, width);
  for (const line of lines) {
    y = ensureSpace(doc, y, size + 5);
    doc.text(line, MARGIN, y);
    y += size + 5;
  }
  return y + 6;
}

function bullet(doc: JsPDFDoc, y: number, text: string): number {
  return paragraph(doc, y, `• ${text}`, { size: 10 });
}

/** Builds a stakeholder PDF for one site. */
export function buildSiteReportPdf(site: SiteInsight): JsPDFDoc {
  const doc = new jsPDF({ unit: "pt", format: "letter" });
  const a = site.analysis!;

  let y = MARGIN;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(14, 165, 233);
  doc.text("GEO", MARGIN, y);
  doc.setTextColor(15, 23, 42);
  doc.text(" Archer", MARGIN + doc.getTextWidth("GEO"), y);
  y += 28;

  doc.setFontSize(16);
  doc.text("AI Visibility Report", MARGIN, y);
  y += 22;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(100, 116, 139);
  doc.text(hostOf(site.url), MARGIN, y);
  y += 14;
  doc.setFontSize(9);
  doc.text(
    `${site.url} · Generated ${new Date().toLocaleDateString()}`,
    MARGIN,
    y
  );
  y += 28;

  y = sectionTitle(doc, y, "Executive summary");
  y = bullet(
    doc,
    y,
    `GEO Score: ${a.geoOverall}/100 (Grade ${gradeFor(a.geoOverall)})`
  );
  y = bullet(doc, y, `AI Understanding: ${a.understanding}/100`);
  if (site.visibility) {
    y = bullet(doc, y, `AI Visibility: ${site.visibility.overall}%`);
  }
  y += 4;
  y = paragraph(doc, y, a.businessSummary, { size: 11, color: [30, 41, 59] });

  y = sectionTitle(doc, y, "GEO component scores");
  for (const c of a.components) {
    y = bullet(doc, y, `${c.name}: ${c.score}/100`);
  }

  y = sectionTitle(doc, y, "Top recommendations");
  for (const [i, r] of a.recommendations.slice(0, 8).entries()) {
    y = paragraph(doc, y, `${i + 1}. ${r.title}`, {
      bold: true,
      size: 10,
      color: [15, 23, 42],
    });
    y = paragraph(
      doc,
      y,
      `${r.impact} impact · ${r.effort} effort · Est. ${estimatedGain(r.impact)}`,
      { size: 9 }
    );
    y = paragraph(doc, y, r.why, { size: 9 });
    y += 4;
  }

  y = sectionTitle(doc, y, "Content opportunities");
  if (a.contentGaps.length === 0) {
    y = paragraph(doc, y, "No content gaps identified in the latest scan.");
  } else {
    for (const g of a.contentGaps) {
      y = paragraph(doc, y, `"${g.question}"`, {
        bold: true,
        size: 10,
        color: [15, 23, 42],
      });
      y = paragraph(doc, y, g.whyItMatters, { size: 9 });
      y += 2;
    }
  }

  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text("Generated by GEO Archer", MARGIN, PAGE_H - 32);

  return doc;
}

export function downloadSiteReportPdf(site: SiteInsight): void {
  const doc = buildSiteReportPdf(site);
  const filename = `geo-archer-report-${hostOf(site.url).replace(/\./g, "-")}.pdf`;
  doc.save(filename);
}
