"use client";

import { useState } from "react";
import { Download, FileBarChart } from "lucide-react";
import { AppShell } from "@/components/AppShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { FadeIn } from "@/components/cards/FadeIn";
import { useInsights, type SiteInsight } from "@/lib/useInsights";
import { estimatedGain, formatDate, gradeFor, hostOf, scoreTone } from "@/lib/utils";

function buildMarkdownReport(site: SiteInsight): string {
  const a = site.analysis!;
  const lines = [
    `# GEO Archer AI Visibility Report — ${hostOf(site.url)}`,
    ``,
    `Generated ${new Date().toLocaleDateString()} · ${site.url}`,
    ``,
    `## Executive summary`,
    ``,
    `- **GEO Score:** ${a.geoOverall}/100 (Grade ${gradeFor(a.geoOverall)})`,
    `- **AI Understanding:** ${a.understanding}/100`,
    site.visibility ? `- **AI Visibility:** ${site.visibility.overall}%` : "",
    ``,
    `> ${a.businessSummary}`,
    ``,
    `## Component scores`,
    ``,
    ...a.components.map((c) => `- ${c.name}: ${c.score}/100`),
    ``,
    `## Top recommendations`,
    ``,
    ...a.recommendations
      .slice(0, 8)
      .map(
        (r, i) =>
          `${i + 1}. **${r.title}** (${r.impact} impact, ${r.effort} effort, est. ${estimatedGain(r.impact)})\n   ${r.why}`
      ),
    ``,
    `## Content opportunities`,
    ``,
    ...a.contentGaps.map((g) => `- "${g.question}" — ${g.whyItMatters}`),
    ``,
    `---`,
    `Generated by GEO Archer.`,
  ];
  return lines.filter((l) => l !== undefined && l !== null).join("\n");
}

export default function ReportsPage() {
  const { data, error, loading } = useInsights();
  const [downloaded, setDownloaded] = useState<string | null>(null);

  function download(site: SiteInsight) {
    const md = buildMarkdownReport(site);
    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const el = document.createElement("a");
    el.href = url;
    el.download = `geo-archer-report-${hostOf(site.url).replace(/\./g, "-")}.md`;
    el.click();
    URL.revokeObjectURL(url);
    setDownloaded(site.siteId);
    setTimeout(() => setDownloaded(null), 2000);
  }

  const ready = (data?.sites ?? []).filter((s) => s.analysis);

  return (
    <AppShell
      title="Reports"
      subtitle="Shareable summaries of each site's AI visibility — built for stakeholders, not crawlers."
    >
      {error && <p className="mb-4 text-sm text-red-600">{error}</p>}
      {loading && <Skeleton className="h-64" />}

      {data &&
        (ready.length === 0 ? (
          <Card className="p-10 text-center">
            <FileBarChart className="mx-auto h-8 w-8 text-slate-300" />
            <p className="mt-3 font-medium text-slate-700">No reports yet</p>
            <p className="mt-1 text-sm text-slate-400">
              Reports become available once a site has a completed analysis.
            </p>
          </Card>
        ) : (
          <FadeIn className="grid gap-4 md:grid-cols-2">
            {ready.map((s) => (
              <Card key={s.siteId} className="flex flex-col p-5">
                <div className="flex items-start justify-between gap-2">
                  <div>
                    <p className="font-semibold text-slate-900">{hostOf(s.url)}</p>
                    <p className="mt-0.5 text-xs text-slate-400">
                      Last analysis{" "}
                      {s.latestScan ? formatDate(s.latestScan.createdAt) : "—"}
                    </p>
                  </div>
                  <Badge tone={scoreTone(s.analysis!.geoOverall)}>
                    GEO {s.analysis!.geoOverall}
                  </Badge>
                </div>
                <p className="mt-3 line-clamp-3 flex-1 text-sm leading-relaxed text-slate-500">
                  {s.analysis!.businessSummary}
                </p>
                <div className="mt-4">
                  <Button variant="secondary" size="sm" onClick={() => download(s)}>
                    <Download className="h-3.5 w-3.5" />
                    {downloaded === s.siteId ? "Downloaded!" : "Export Report (.md)"}
                  </Button>
                </div>
              </Card>
            ))}
          </FadeIn>
        ))}
    </AppShell>
  );
}
